variable "gcp_account_id" {}
variable "public_instance_name" {}
variable "public_instance_type" {}
variable "public_instance_zone" {}
variable "network_interface" {}
variable "private_key_path" {}
variable "public_key_path" {}
variable "public_instance_image" {}
variable "public_subnet" {}
variable "script_path" {}
variable "disk_type" {}
variable "disk_size" {}
variable "network_tags" {}
variable "ports" {}
variable "porotocol" {}
variable "source_range" {}
variable "firewall_name" {}